### ISSUE TITLE
【重要】ホストに繋がらなくなる

### ISSUE THREAD

**Issue by shimamura10** [Rei1449/geekhack-vol2#54]
時々ホストにつながらなくなってしまう
localhost:5173へのアクセスがすべて出来なくなり、dockerを再起動しても治らない。PCを再起動すると治る。

**Comment by shimamura10** [comment]
2024-05-04 01:23:44 ERROR:    Exception in ASGI application
2024-05-04 01:23:44 Traceback (most recent call last):
2024-05-04 01:23:44   File "/app/backend/./src/routers/websocket.py", line 123, in websocket_endpoint
2024-05-04 01:23:44     data = await websocket.receive_text()
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/websockets.py", line 138, in receive_text
2024-05-04 01:23:44     self._raise_on_disconnect(message)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/websockets.py", line 130, in _raise_on_disconnect
2024-05-04 01:23:44     raise WebSocketDisconnect(message["code"], message.get("reason"))
2024-05-04 01:23:44 starlette.websockets.WebSocketDisconnect: (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
2024-05-04 01:23:44 
2024-05-04 01:23:44 During handling of the above exception, another exception occurred:
2024-05-04 01:23:44 
2024-05-04 01:23:44 Traceback (most recent call last):
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 203, in run_asgi
2024-05-04 01:23:44     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
2024-05-04 01:23:44     return await self.app(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-04 01:23:44     await super().__call__(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
2024-05-04 01:23:44     await self.middleware_stack(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 151, in __call__
2024-05-04 01:23:44     await self.app(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 77, in __call__
2024-05-04 01:23:44     await self.app(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-04 01:23:44     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-04 01:23:44     raise exc
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-04 01:23:44     await app(scope, receive, sender)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
2024-05-04 01:23:44     await self.middleware_stack(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
2024-05-04 01:23:44     await route.handle(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 373, in handle
2024-05-04 01:23:44     await self.app(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 96, in app
2024-05-04 01:23:44     await wrap_app_handling_exceptions(app, session)(scope, receive, send)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-04 01:23:44     raise exc
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-04 01:23:44     await app(scope, receive, sender)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 94, in app
2024-05-04 01:23:44     await func(session)
2024-05-04 01:23:44   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 348, in app
2024-05-04 01:23:44     await dependant.call(**values)
2024-05-04 01:23:44   File "/app/backend/./src/routers/websocket.py", line 126, in websocket_endpoint
2024-05-04 01:23:44     if confilm_host[0] == client_name:
2024-05-04 01:23:44 IndexError: list index out of range
こんな感じのエラーが無限に繰り返されてる
